"""Kronos — Financial OHLCV forecasting via shiyu-coder/Kronos foundation model.

Kronos (AAAI 2026) is the first open-source foundation model trained on data from
45+ global exchanges. It generates full OHLCV forecasts autoregressively.

Installation (no PyPI package — clone alongside this project):
    git clone https://github.com/shiyu-coder/Kronos.git vendor/kronos
    pip install -r vendor/kronos/requirements.txt
    KRONOS_REPO_PATH=vendor/kronos   # add to .env

Models (all from HuggingFace NeoQuasar org):
    NeoQuasar/Kronos-mini   —  4.1M params, 2048 ctx  (fastest)
    NeoQuasar/Kronos-small  — 24.7M params,  512 ctx  (default)
    NeoQuasar/Kronos-base   — 102.3M params, 512 ctx  (most accurate)

Falls back to pure-Python GBM Monte Carlo if Kronos is not available.
Model singleton is cached at module level — loads once per process.
"""

from __future__ import annotations

import json
import math
import os
import random
import sys
from datetime import datetime, timedelta
from typing import Any

import aiohttp

from crypto_oracle.agents.base import BaseAgent
from crypto_oracle.models.signals import AgentSignal
from crypto_oracle.utils.logger import get_logger

logger = get_logger(__name__)

_SYSTEM = """You are Kronos, a quantitative trading agent powered by a financial OHLCV
foundation model trained on 45+ global exchanges (AAAI 2026).

You receive a 7-day OHLCV forecast generated by sampling multiple paths from the model.
Key metrics:
- median_return_7d_pct: expected close-to-close return
- bullish_probability: fraction of sampled paths where close > current
- implied_range_pct: (max predicted high - min predicted low) / current — volatility proxy
- predicted_high_7d / predicted_low_7d: best/worst case bounds from sampled paths
- volume_trend: predicted volume relative to recent average

Respond ONLY in this exact format (no extra text):
SIGNAL: BULLISH|BEARISH|NEUTRAL
CONFIDENCE: 0.XX
SUMMARY: one or two sentences referencing specific forecast numbers
DATA_POINTS: point1 | point2 | point3"""


# ---------------------------------------------------------------------------
# Model singleton
# ---------------------------------------------------------------------------

_predictor = None
_predictor_loaded = False


def _get_device() -> str:
    try:
        import torch
        if torch.cuda.is_available():
            return "cuda"
        if torch.backends.mps.is_available():
            return "mps"
    except ImportError:
        pass
    return "cpu"


def _load_predictor():
    global _predictor, _predictor_loaded
    if _predictor_loaded:
        return _predictor

    repo_path = os.getenv("KRONOS_REPO_PATH", "vendor/kronos")
    if not os.path.isdir(repo_path):
        logger.warning(
            "Kronos repo not found at %s — using GBM fallback. "
            "Run: git clone https://github.com/shiyu-coder/Kronos.git %s",
            repo_path, repo_path,
        )
        _predictor_loaded = True
        return None

    if repo_path not in sys.path:
        sys.path.insert(0, repo_path)

    model_name = os.getenv("KRONOS_MODEL", "NeoQuasar/Kronos-small")
    tokenizer_name = os.getenv(
        "KRONOS_TOKENIZER",
        "NeoQuasar/Kronos-Tokenizer-2k"
        if "mini" in model_name
        else "NeoQuasar/Kronos-Tokenizer-base",
    )
    device = _get_device()

    try:
        from model import Kronos, KronosPredictor, KronosTokenizer  # type: ignore

        logger.info("Loading Kronos model %s on %s …", model_name, device)
        tokenizer = KronosTokenizer.from_pretrained(tokenizer_name)
        model = Kronos.from_pretrained(model_name)

        max_context = 2048 if "mini" in model_name else 512
        _predictor = KronosPredictor(
            model, tokenizer, device=device, max_context=max_context
        )
        logger.info("Kronos predictor loaded successfully (%s)", model_name)
    except Exception as exc:
        logger.warning(
            "Kronos load failed (%s) — using GBM Monte Carlo fallback", exc
        )
        _predictor = None

    _predictor_loaded = True
    return _predictor


# ---------------------------------------------------------------------------
# Symbol maps
# ---------------------------------------------------------------------------

_BINANCE_MAP = {
    "BTC": "BTCUSDT", "ETH": "ETHUSDT", "SOL": "SOLUSDT",
    "ADA": "ADAUSDT", "DOGE": "DOGEUSDT", "XRP": "XRPUSDT",
    "AVAX": "AVAXUSDT", "LTC": "LTCUSDT",
}


# ---------------------------------------------------------------------------
# Agent
# ---------------------------------------------------------------------------

class KronosAgent(BaseAgent):
    name = "Kronos"

    async def fetch_data(self, symbol: str) -> dict[str, Any]:
        ohlcv = await self._fetch_ohlcv(symbol)
        if len(ohlcv) < 30:
            return {"ohlcv": ohlcv, "forecast": {}, "method": "insufficient_data"}

        predictor = _load_predictor()
        if predictor is not None:
            forecast = await self._kronos_forecast(predictor, ohlcv)
            method = "kronos"
        else:
            forecast = _gbm_monte_carlo([c["close"] for c in ohlcv])
            method = "gbm_monte_carlo"

        return {
            "current_price": ohlcv[-1]["close"],
            "ohlcv_tail": ohlcv[-7:],
            "forecast": forecast,
            "method": method,
        }

    async def _fetch_ohlcv(self, symbol: str) -> list[dict]:
        """Fetch daily OHLCV from Binance klines (free, no auth needed)."""
        pair = _BINANCE_MAP.get(symbol.upper(), f"{symbol.upper()}USDT")
        url = (
            f"https://api.binance.com/api/v3/klines"
            f"?symbol={pair}&interval=1d&limit=400"
        )
        try:
            async with aiohttp.ClientSession() as session:
                async with session.get(
                    url, timeout=aiohttp.ClientTimeout(total=15)
                ) as r:
                    raw = await r.json()

            return [
                {
                    "timestamp": datetime.utcfromtimestamp(k[0] / 1000),
                    "open":  float(k[1]),
                    "high":  float(k[2]),
                    "low":   float(k[3]),
                    "close": float(k[4]),
                    "volume": float(k[5]),
                }
                for k in raw
            ]
        except Exception as exc:
            logger.warning("Binance OHLCV fetch failed for %s: %s", symbol, exc)
            return []

    async def _kronos_forecast(
        self, predictor: Any, ohlcv: list[dict]
    ) -> dict[str, Any]:
        import asyncio

        def _sync() -> dict:
            import pandas as pd

            df = pd.DataFrame(ohlcv)[["open", "high", "low", "close", "volume"]]
            x_timestamp = pd.Series([row["timestamp"] for row in ohlcv])

            last_ts = ohlcv[-1]["timestamp"]
            y_timestamp = pd.Series(
                [last_ts + timedelta(days=i + 1) for i in range(7)]
            )

            # Use sample_count=10 to get a forecast distribution
            pred_df = predictor.predict(
                df=df,
                x_timestamp=x_timestamp,
                y_timestamp=y_timestamp,
                pred_len=7,
                T=1.0,
                top_p=0.9,
                sample_count=10,
                verbose=False,
            )

            current_close = ohlcv[-1]["close"]
            avg_volume = sum(r["volume"] for r in ohlcv[-14:]) / 14

            pred_closes = pred_df["close"].tolist()
            pred_highs  = pred_df["high"].tolist()
            pred_lows   = pred_df["low"].tolist()
            pred_vols   = pred_df["volume"].tolist() if "volume" in pred_df else []

            median_close_7d = pred_closes[-1]
            median_return   = (median_close_7d - current_close) / current_close

            # Bullish probability: fraction of the 7-day path above current
            # (using day-by-day close trajectory)
            days_above = sum(1 for c in pred_closes if c > current_close)
            bullish_prob = days_above / len(pred_closes)

            implied_range_pct = (
                (max(pred_highs) - min(pred_lows)) / current_close * 100
            )

            vol_trend = (
                (sum(pred_vols) / len(pred_vols) / avg_volume - 1) * 100
                if pred_vols and avg_volume > 0
                else None
            )

            return {
                "current_close": round(current_close, 2),
                "median_return_7d_pct": round(median_return * 100, 3),
                "median_close_7d": round(median_close_7d, 2),
                "predicted_high_7d": round(max(pred_highs), 2),
                "predicted_low_7d": round(min(pred_lows), 2),
                "bullish_probability": round(bullish_prob, 3),
                "implied_range_pct": round(implied_range_pct, 2),
                "volume_trend_pct": round(vol_trend, 1) if vol_trend is not None else None,
                "predicted_ohlc_path": [
                    {
                        "day": i + 1,
                        "open":  round(pred_df["open"].iloc[i], 2),
                        "high":  round(pred_df["high"].iloc[i], 2),
                        "low":   round(pred_df["low"].iloc[i], 2),
                        "close": round(pred_df["close"].iloc[i], 2),
                    }
                    for i in range(len(pred_df))
                ],
            }

        return await asyncio.to_thread(_sync)

    async def analyze(self, symbol: str, data: dict[str, Any]) -> AgentSignal:
        fc   = data.get("forecast", {})
        method = data.get("method", "unknown")
        current = data.get("current_price", 0)

        # Don't send the full path to Claude — just the summary metrics
        fc_summary = {k: v for k, v in fc.items() if k != "predicted_ohlc_path"}

        prompt = (
            f"Symbol: {symbol}\n"
            f"Current price: ${current:,.2f}\n"
            f"Forecast method: {method}\n"
            f"7-day OHLCV forecast summary:\n"
            f"{json.dumps(fc_summary, indent=2)}\n\n"
            "Analyse this probabilistic OHLCV forecast and produce your signal."
        )
        text = await self._call_claude(_SYSTEM, prompt)
        signal, confidence, summary, data_points = self._parse_signal_from_text(text)
        return AgentSignal(
            agent_name=self.name,
            signal=signal,
            confidence=confidence,
            summary=summary,
            data_points=data_points,
        )


# ---------------------------------------------------------------------------
# GBM Monte Carlo fallback
# ---------------------------------------------------------------------------

def _gbm_monte_carlo(prices: list[float]) -> dict[str, Any]:
    returns = [
        (prices[i] - prices[i - 1]) / prices[i - 1]
        for i in range(1, len(prices))
    ]
    mu    = sum(returns) / len(returns)
    sigma = math.sqrt(
        sum((r - mu) ** 2 for r in returns) / max(len(returns) - 1, 1)
    )
    current  = prices[-1]
    n_paths  = 2000
    horizon  = 7
    endpoints, highs, lows = [], [], []

    for _ in range(n_paths):
        price   = current
        path_hi = current
        path_lo = current
        for _ in range(horizon):
            price   *= math.exp((mu - 0.5 * sigma ** 2) + sigma * random.gauss(0, 1))
            path_hi  = max(path_hi, price)
            path_lo  = min(path_lo, price)
        endpoints.append(price)
        highs.append(path_hi)
        lows.append(path_lo)

    endpoints.sort()
    n        = len(endpoints)
    median   = endpoints[n // 2]
    bullish  = sum(1 for e in endpoints if e > current) / n
    sharpe   = (mu / sigma * math.sqrt(365)) if sigma > 0 else 0

    return {
        "current_close":        round(current, 2),
        "median_return_7d_pct": round((median - current) / current * 100, 3),
        "median_close_7d":      round(median, 2),
        "predicted_high_7d":    round(sorted(highs)[int(0.9 * n)], 2),
        "predicted_low_7d":     round(sorted(lows)[int(0.1 * n)], 2),
        "bullish_probability":  round(bullish, 3),
        "implied_range_pct":    round((max(highs) - min(lows)) / current * 100, 2),
        "sharpe_annualised":    round(sharpe, 3),
        "note":                 "GBM Monte Carlo fallback (Kronos repo not found at KRONOS_REPO_PATH)",
    }
